#!/bin/env sh
if [ -f "/config/.initialized" ]; then
    echo "Config already initialized"
else
    echo "Initializing config"
    /usr/bin/gs-server /profile=${DIRECTORY_CONFIG:=/config} /set-admin="${ADMIN_USERNAME}:${ADMIN_PASSWORD}" /console &
    PID=$!
    sleep 10
    kill $PID
    # Enable remote access
    sed -i 's/WebUiLocalOnly = Yes/WebUiLocalOnly = No/' /config/settings.tix
    touch /config/.initialized
    sleep 3
fi

/usr/bin/gs-server /profile=${DIRECTORY_CONFIG:=/config} /console

