name: build-alpine-core
run-name: Alpine Core - ${{ github.actor }} by ${{ github.event_name }} ${{ github.ref }}
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "alpine-core/**"
      - "!alpine-core/README.md"
  pull_request:
    branches:
      - master
    paths:
      - "alpine-core/**"
      - "!alpine-core/README.md"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        id: version
        with:
          change_path: "alpine-core"
          namespace: "alpine-core"

      - name: Echo Version
        run: echo "Version would be ${{ steps.version.outputs.version }}"

      - name: Build and Push Docker Master Branch
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:alpine-core"
          push: true
          tags: faliarin/alpine-core:latest,faliarin/alpine-core:${{ steps.version.outputs.version }}
          provenance: mode=max
          sbom: true

      # Instead of tagging on merge, we are tagging on release or manually
      - name: Tag Release (vX.Y.Z)
        if: ${{ (github.event_name != 'pull_request') && (steps.version.outputs.changed == true) }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}
