name: build-goodsync
run-name: Goodsync - ${{ github.actor }} by ${{ github.event_name }} ${{ github.ref }}
on:
  push:
    branches:
    - 'master'
    paths:
    - 'goodsync/**'
  pull_request:
    branches:
    - master
    paths:
    - 'goodsync/**'
    

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.0.0-beta2
        id: version
        with:
          change_path: "goodsync"
          namespace: "goodsync"

      - name: Echo Version
        run: echo "Version would be ${{ steps.version.outputs.version }}"

      - name: Build and Push Docker PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          context: "{{defaultContext}}:goodsync"
          push: false
          tags: faliarin/goodsync:latest,faliarin/goodsync:${{ steps.version.outputs.version }}
      
      - name: Build and Push Docker Master Branch
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          context: "{{defaultContext}}:goodsync"
          push: true
          tags: faliarin/goodsync:latest,faliarin/goodsync:${{ steps.version.outputs.version }}

      - name: Tag Release (vX.Y.Z)
        if: github.event_name != 'pull_request'
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}