name: build-ubuntu-core
run-name: ${{ github.actor }} kicked off a build.
on:
  push:
    branches:
    - 'master'
    paths:
    - 'ubuntu-core/**'
    - '.github/workflows/hub-uploads.yml'
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          change_path: "ubuntu-core"

      -
        name: Build and push general
        run: echo "Version would be "${{ steps.version.outputs.version }}"
      # https://github.com/marketplace/actions/build-and-push-docker-images
      # -
      #   name: Build and push general
      #   uses: docker/build-push-action@v3
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     context: "{{defaultContext}}:ubuntu-core"
      #     push: true
      #     tags: faliarin/ubuntu-core:latest,faliarin/ubuntu-core:${{ steps.versioning.outputs.version }}

