name: build-ubuntu-core
run-name: ${{ github.actor }} kicked off a build.
on:
  push:
    branches:
    - 'master'
    - 'test-branch'
    paths:
    - 'ubuntu-core/**'
    - '.github/workflows/hub-uploads.yml'
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.0.0-beta2
        id: version
        with:
          change_path: "ubuntu-core"
          namespace: "ubuntu-core"

      - name: Echo Version
        run: echo "Version would be ${{ steps.version.outputs.version }}"

      - name: Build and Push Docker
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:ubuntu-core"
          push: false
          tags: faliarin/ubuntu-core:latest,faliarin/ubuntu-core:${{ steps.version.outputs.version }}

      - name: Tag Release (vX.Y.Z)
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}