name: build-tintin
run-name: Tintin Build kicked off by ${{ github.actor }}
on:
  push:
    branches:
    - 'master'
    paths:
    - 'tintin/**'
  pull_request:
    branches:
      - master
    

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.0.0-beta2
        id: version
        with:
          change_path: "tintin"
          namespace: "tintin"

      - name: Echo Version
        run: echo "Version would be ${{ steps.version.outputs.version }}"

      - name: Build and Push Docker PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,wasi/wasm32
          context: "{{defaultContext}}:tintin"
          push: false
          tags: faliarin/tintin:latest,faliarin/tintin:${{ steps.version.outputs.version }}
      
      - name: Build and Push Docker Master Branch
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:tintin"
          push: true
          tags: faliarin/tintin:latest,faliarin/tintin:${{ steps.version.outputs.version }}

      - name: Docker Hub Description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: faliarin/tintin
          readme-filepath: tintin/README.md

      - name: Tag Release (vX.Y.Z)
        if: github.event_name != 'pull_request'
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}